language: c
compiler:
    - gcc
    - clang
before_install:
    - sudo apt-get update -qq
    - sudo apt-get remove -qq libzmq3 libzmq3-dev
    - sudo apt-get install -qq lua5.2 liblua5.2-dev libssl-dev libzmq-dev libevent-dev
script: "scons && source ./test/test_all.sh"
